[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent_of_code_2023"
path = "src/lib.rs"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.10.2"
